//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibilizm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string ArticleNumber { get; set; }
        public Nullable<decimal> MinCostForAgent { get; set; }
        public Nullable<int> Koli { get; set; }
    }
}
